name = "doctr-test-reverse-proxy"
compatibility_date = "2024-02-07"
main = "src/index.ts"

routes = [{ pattern = "homeostasis.fr", custom_domain = true },{ pattern = "www.homeostasis.fr", custom_domain = true },{ pattern = "webflow.homeostasis.fr/*", zone_name = "homeostasis.fr" },{ pattern = "www.homeostasis.fr/*", zone_name = "homeostasis.fr" },{ pattern = "app.homeostasis.fr/*", zone_name = "homeostasis.fr" },{ pattern = "static-maps.homeostasis.fr/*", zone_name = "homeostasis.fr" },{ pattern = "establishments.homeostasis.fr/*", zone_name = "homeostasis.fr" },{ pattern = "resources.homeostasis.fr/*", zone_name = "homeostasis.fr" },{ pattern = "seo.homeostasis.fr/*", zone_name = "homeostasis.fr" }]

[[r2_buckets]]
binding = 'ROOT'                  # <~ do not change, else proxy will break
bucket_name = 'doctr-test-bucket'

[vars]
DOMAIN = "homeostasis.fr"
SUBDOMAINS = "app, static-maps, establishments, resources, seo"
WEBFLOW_SUBDOMAIN = "webflow"
S3_BUCKET_NAME = "doctr-bucket-test.s3.eu-west-3.amazonaws.com"
ELASTIC_BEANSTALK_URL = "backend-docker-prod-web.kfvghvqmav.ca-central-1.elasticbeanstalk.com"
