name = "thind-proxy"
compatibility_date = "2024-02-07"
main ="src/index.ts"

[vars]
DOMAIN = "REPLACE_WITH_MAIN_DOMAIN"
SUBDOMAINS = "uselooop, stripe"
WEBFLOW_SUBDOMAIN = "REPLACE_WITH_MAIN_SUB_DOMAIN"
ROOT_FILES = "subfolder.json, sitemap.xml"
R2PATH = "REPLACE_WITH_PATH_OF_R2_STOAGE"
 